### PR TITLE
feat: Replace react-helmet with Gatsby Head API

### PR DESCRIPTION
**Pull request by huntermacd**
This diff pulls `react-helmet` and the associated Gatsby-specific plugin `gatsby-plugin-react-helmet` out of the project, bumps the version of Gatsby to the newest v4 release (they're on v5 now) in order to add support for the Gatsby Head API, and replaces the bits of code that used `react-hemet` with bits of code that utilize [Gatsby's Head API](https://www.gatsbyjs.com/blog/introducing-the-gatsby-head-api/), which is the new preferred method.

Motivation: the `gatsby-plugin-react-helmet` plugin is causing issues for a client project and it's a soon-to-be-deprecated package anyway.

Note: eslint doesn't like it when you create an explicit `children` prop, but we need to preserve the existing functionality in the new `Head` function, so I added an ignore. Open to ideas of a more elegant way to accomplish this. Perhaps a unique prop name would allow for the same thing without the warning.

### CODE REVIEW

**Comment by e0ipso** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr71-oavua16hxecr4sri8x5dv69zrks3llau.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6390e87ce2e14d36b51c1983

Visual Diffs:
- https://dashboard.tugboatqa.com/6390e87ce2e14d36b51c1983/visualdiffs

**Review by andy-blum — CHANGES_REQUESTED** [review]
This looks like it's following the gatsby docs, but the resulting page has the markup in weird places.

On the live site, both the `<title>` and `<meta name="description">` are in the document head
Screenshot 2022-12-07 at 2 57 20 PM

But in the tugboat preview on this page those elements are in the document body

Screenshot 2022-12-07 at 2 54 58 PM

I'm not sure if this has any meaningful impact (the browser seems to use the title's textContent just fine), but I don't think this is intentional.

**Comment by huntermacd** [comment]
Hrm, yeah, good catch. Will revisit this later, then.

**Comment by e0ipso** [comment]
I opened a PR for this as well in #76.

**Comment by e0ipso** [comment]
This was fixed in #76.

**Pull request closed without merging**
